# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'MAVEN_CENTRAL'

steps:  
- task: Gradle@2
  displayName: 'Build and Test'
  inputs:    
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease test'

- task: Gradle@2
  displayName: 'Publish to Maven Central'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'publish --no-daemon --no-parallel'
  env:
    ORG_GRADLE_PROJECT_mavenCentralUsername: $(mavenCentralUsername)
    ORG_GRADLE_PROJECT_mavenCentralPassword: $(mavenCentralPassword)
    ORG_GRADLE_PROJECT_signingInMemoryKey: $(signingInMemoryKey)
    ORG_GRADLE_PROJECT_signingInMemoryKeyId: $(signingInMemoryKeyId)
    ORG_GRADLE_PROJECT_signingInMemoryPassword: $(signingInMemoryPassword)

- task: Gradle@2
  displayName: 'Release library'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'closeAndReleaseRepository'
  env:
    ORG_GRADLE_PROJECT_mavenCentralUsername: $(mavenCentralUsername)
    ORG_GRADLE_PROJECT_mavenCentralPassword: $(mavenCentralPassword)
    ORG_GRADLE_PROJECT_signingInMemoryKey: $(signingInMemoryKey)
    ORG_GRADLE_PROJECT_signingInMemoryKeyId: $(signingInMemoryKeyId)
    ORG_GRADLE_PROJECT_signingInMemoryPassword: $(signingInMemoryPassword)